# Generated by Django 3.2.4 on 2023-07-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=150)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('especie', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(max_length=20)),
                ('telefone3', models.CharField(max_length=20)),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
