# Generated by Django 3.2.4 on 2023-07-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('promotora', models.CharField(blank=True, max_length=255, null=True)),
                ('data_de_digitacao', models.DateTimeField(blank=True, null=True)),
                ('numero_do_contrato', models.FloatField(blank=True, null=True)),
                ('nome_do_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('convenio', models.CharField(blank=True, max_length=255, null=True)),
                ('operacao', models.CharField(blank=True, max_length=255, null=True)),
                ('banco', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_do_contrato', models.FloatField(blank=True, null=True)),
                ('qtd_de_parcelas', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_da_parcela', models.CharField(blank=True, max_length=255, null=True)),
                ('data_pag_ao_cliente', models.DateTimeField(blank=True, null=True)),
                ('data_pag_comissao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_da_comissao', models.FloatField(blank=True, null=True)),
                ('porcentagem', models.FloatField(blank=True, null=True)),
                ('corretor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='especie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
