# Generated by Django 3.2.4 on 2023-07-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230713_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='data_de_digitacao',
            new_name='dt_digitacao',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='data_pag_ao_cliente',
            new_name='dt_pag_cliente',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='data_pag_comissao',
            new_name='dt_pag_comissao',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='nome_do_cliente',
            new_name='no_cliente',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='numero_do_contrato',
            new_name='nr_contrato',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='qtd_de_parcelas',
            new_name='qt_parcelas',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_da_comissao',
            new_name='vl_comissao',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_do_contrato',
            new_name='vl_contrato',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_da_parcela',
            new_name='vl_parcela',
        ),
    ]
