# Generated by Django 3.2.4 on 2023-07-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230713_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nr_contrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
