# Generated by Django 3.2.4 on 2023-07-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contrato_nr_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_vencimento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
