# Generated by Django 3.2.4 on 2023-07-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_emprestimo', models.DateField(blank=True, null=True)),
                ('no_cliente', models.CharField(blank=True, max_length=255)),
                ('vl_emprestimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qt_parcela', models.IntegerField(blank=True, null=True)),
                ('tp_pagamento', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='porcentagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vl_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vl_contrato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
