# Generated by Django 3.2.4 on 2023-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230714_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='natureza_despesa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tp_despesa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
