# Generated by Django 3.2.4 on 2023-07-15 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230715_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tp_pagamento',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='qt_parcela',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.CreateModel(
            name='EmprestimoItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_vencimento', models.DateField(blank=True, null=True)),
                ('nr_parcela', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('dt_pagamento', models.DateField(blank=True, null=True)),
                ('emprestimo', models.ForeignKey(help_text='Emprestimo', on_delete=django.db.models.deletion.CASCADE, related_name='EmprestimoItem', to='core.emprestimo', verbose_name='Emprestimo')),
            ],
        ),
    ]
