# Generated by Django 3.2.4 on 2023-07-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230715_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='dt_digitacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dt_pag_cliente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='dt_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
