# Generated by Django 3.2.4 on 2023-07-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230717_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='dt_vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
