# Generated by Django 3.2.4 on 2023-07-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_contrato_vl_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimoitem',
            name='tp_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
